/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DailyArticlePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var MODEL_OPTIONS = {
  "deepseek-v4-flash": "DeepSeek V4 Flash (\u9ED8\u8BA4\uFF0C\u5FEB\u901F\u7ECF\u6D4E)",
  "deepseek-v4-pro": "DeepSeek V4 Pro\uFF08\u6700\u5F3A\uFF0C\u66F4\u8D35\uFF09",
  "deepseek-chat": "deepseek-chat\uFF08\u65E7\u7248\uFF0C2026-07-24 \u505C\u7528\uFF09",
  "deepseek-reasoner": "deepseek-reasoner\uFF08\u65E7\u7248\uFF0C2026-07-24 \u505C\u7528\uFF09"
};
var DEFAULT_SETTINGS = {
  deepseekApiKey: "",
  model: "deepseek-v4-flash",
  arxivCategories: "cs.AI\ncs.CL\ncs.CV\ncs.LG",
  fetchTime: "08:00",
  maxResultsPerCategory: 50,
  topN: 10,
  outputFolder: "DailyArticle",
  outputLanguage: "zh-CN"
};
var DailyArticleSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("DeepSeek API Key").setDesc("DeepSeek API \u5BC6\u94A5\uFF0C\u7528\u4E8E\u8BBA\u6587\u6253\u5206\u548C\u6458\u8981\u751F\u6210").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("sk-...").setValue(this.plugin.settings.deepseekApiKey).onChange(async (value) => {
        this.plugin.settings.deepseekApiKey = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("DeepSeek \u6A21\u578B").setDesc("\u7528\u4E8E\u8BBA\u6587\u6253\u5206\u548C\u6458\u8981\u751F\u6210\u7684\u6A21\u578B\u3002V4 Flash \u6027\u4EF7\u6BD4\u6700\u9AD8").addDropdown((dropdown) => {
      for (const value of Object.keys(MODEL_OPTIONS)) {
        dropdown.addOption(value, MODEL_OPTIONS[value]);
      }
      dropdown.setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Arxiv \u5206\u7C7B").setDesc("\u6BCF\u884C\u4E00\u4E2A Arxiv \u5206\u7C7B\u6807\u7B7E\uFF0C\u4F8B\u5982 cs.AI\u3001cs.CL\u3001cs.CV\u3001cs.LG").addTextArea(
      (text) => text.setPlaceholder("cs.AI\ncs.CL\ncs.CV\ncs.LG").setValue(this.plugin.settings.arxivCategories).onChange(async (value) => {
        this.plugin.settings.arxivCategories = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5B9A\u65F6\u83B7\u53D6\u65F6\u95F4").setDesc("\u6BCF\u65E5\u81EA\u52A8\u83B7\u53D6\u8BBA\u6587\u7684\u65F6\u95F4\uFF0824 \u5C0F\u65F6\u5236\uFF09").addText(
      (text) => text.setPlaceholder("08:00").setValue(this.plugin.settings.fetchTime).onChange(async (value) => {
        this.plugin.settings.fetchTime = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6BCF\u7C7B\u6700\u5927\u83B7\u53D6\u6570").setDesc("\u6BCF\u4E2A\u5206\u7C7B\u6700\u591A\u83B7\u53D6\u7684\u8BBA\u6587\u6570\u91CF").addText(
      (text) => text.setPlaceholder("50").setValue(String(this.plugin.settings.maxResultsPerCategory)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.maxResultsPerCategory = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u7CBE\u9009\u6570\u91CF").setDesc("\u6BCF\u65E5\u7CBE\u9009\u8BBA\u6587\u6570\u91CF").addText(
      (text) => text.setPlaceholder("10").setValue(String(this.plugin.settings.topN)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.topN = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u8F93\u51FA\u6587\u4EF6\u5939").setDesc("\u751F\u6210\u7684 Markdown \u6587\u4EF6\u5B58\u653E\u8DEF\u5F84\uFF08\u76F8\u5BF9\u4E8E vault \u6839\u76EE\u5F55\uFF09").addText(
      (text) => text.setPlaceholder("DailyArticle").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
        this.plugin.settings.outputFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u8F93\u51FA\u8BED\u8A00").setDesc("\u751F\u6210\u62A5\u544A\u7684\u6458\u8981\u548C\u89E3\u6790\u8BED\u8A00").addDropdown(
      (dropdown) => dropdown.addOption("zh-CN", "\u4E2D\u6587").addOption("en", "English").setValue(this.plugin.settings.outputLanguage).onChange(async (value) => {
        this.plugin.settings.outputLanguage = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/arxiv.ts
function pad(n) {
  return n.toString().padStart(2, "0");
}
function formatDate(date) {
  const y = date.getFullYear();
  const m = pad(date.getMonth() + 1);
  const d = pad(date.getDate());
  const hh = pad(date.getHours());
  const mm = pad(date.getMinutes());
  return `${y}${m}${d}${hh}${mm}`;
}
function truncate(str, maxLen) {
  if (str.length <= maxLen)
    return str;
  return str.slice(0, maxLen) + "...";
}
function decodeXmlEntities(str) {
  return str.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&apos;/g, "'");
}
function parseAtomXml(xml) {
  var _a, _b, _c, _d, _e, _f;
  const parser = new DOMParser();
  const doc = parser.parseFromString(xml, "text/xml");
  const entries = doc.querySelectorAll("entry");
  const papers = [];
  const totalResultsEl = doc.querySelector("totalResults") || doc.querySelector("opensearch\\:totalResults");
  const totalResults = totalResultsEl ? parseInt(totalResultsEl.textContent || "0") : entries.length;
  for (const entry of Array.from(entries)) {
    const idEl = entry.querySelector("id");
    const titleEl = entry.querySelector("title");
    const summaryEl = entry.querySelector("summary");
    const publishedEl = entry.querySelector("published");
    const authorEls = entry.querySelectorAll("author name");
    const authors = Array.from(authorEls).map(
      (el) => el.textContent || ""
    );
    const linkEl = entry.querySelector("link[title='pdf']");
    const link = linkEl ? linkEl.getAttribute("href") || "" : ((_a = idEl == null ? void 0 : idEl.textContent) == null ? void 0 : _a.replace("http:", "https:")) || "";
    let catEl = entry.querySelector("primary_category") || entry.querySelector("arxiv\\:primary_category");
    const category = catEl ? catEl.getAttribute("term") || "" : ((_b = entry.querySelector("category")) == null ? void 0 : _b.getAttribute("term")) || "";
    const id = ((_c = idEl == null ? void 0 : idEl.textContent) == null ? void 0 : _c.trim()) || "";
    const title = decodeXmlEntities(
      (((_d = titleEl == null ? void 0 : titleEl.textContent) == null ? void 0 : _d.trim()) || "").replace(/\s+/g, " ")
    );
    const summary = decodeXmlEntities(
      (((_e = summaryEl == null ? void 0 : summaryEl.textContent) == null ? void 0 : _e.trim()) || "").replace(/\s+/g, " ")
    );
    const published = ((_f = publishedEl == null ? void 0 : publishedEl.textContent) == null ? void 0 : _f.trim()) || "";
    papers.push({ id, title, summary, authors, published, link, category });
  }
  return { entries: papers, totalResults };
}
async function queryArxiv(query, maxResults) {
  const params = new URLSearchParams({
    search_query: query,
    start: "0",
    max_results: String(maxResults),
    sortBy: "submittedDate",
    sortOrder: "descending"
  });
  const url = `http://export.arxiv.org/api/query?${params.toString()}`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Arxiv API error: ${response.status} ${response.statusText}`);
  }
  const xml = await response.text();
  return parseAtomXml(xml);
}
async function fetchPapersByCategory(category, maxResults) {
  const now = new Date();
  const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1e3);
  const dateRange = `submittedDate:[${formatDate(yesterday)} TO ${formatDate(now)}]`;
  const query = `cat:${category.trim()} AND ${dateRange}`;
  const result = await queryArxiv(query, maxResults);
  return result.entries;
}
async function fetchPapersByCategories(categories, maxResultsPerCategory) {
  const seen = /* @__PURE__ */ new Set();
  const allPapers = [];
  for (const category of categories) {
    try {
      const papers = await fetchPapersByCategory(category, maxResultsPerCategory);
      for (const paper of papers) {
        if (!seen.has(paper.id)) {
          seen.add(paper.id);
          allPapers.push(paper);
        }
      }
    } catch (e) {
      console.error(`Failed to fetch category ${category}:`, e);
    }
  }
  return allPapers;
}
function preparePaperForScoring(papers) {
  return papers.map((p) => ({
    id: p.id,
    title: p.title,
    summary: truncate(p.summary, 300)
  }));
}

// src/deepseek.ts
var DEEPSEEK_BASE_URL = "https://api.deepseek.com";
async function callDeepSeek(apiKey, model, systemPrompt, userMessage) {
  const messages = [
    { role: "system", content: systemPrompt },
    { role: "user", content: userMessage }
  ];
  const response = await fetch(`${DEEPSEEK_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model,
      messages,
      response_format: { type: "json_object" },
      temperature: 0.3,
      max_tokens: 4096
    })
  });
  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(
      `DeepSeek API error: ${response.status} ${response.statusText}
${errorBody}`
    );
  }
  const data = await response.json();
  return data.choices[0].message.content;
}
async function scorePapers(apiKey, model, papers, language) {
  const prepared = preparePaperForScoring(papers);
  const langHint = language === "zh-CN" ? "\u4E2D\u6587" : "English";
  const systemPrompt = `You are an AI research assistant that evaluates Arxiv papers. Score each paper on a scale of 1-10 based on:
- Novelty and significance of the contribution
- Potential impact on the field
- Quality of the research
- Relevance to current AI/ML trends

Return a JSON object with a "papers" array: [{ "id": "paper_id", "score": number, "reason": "brief explanation in ${langHint}" }]

Score guidelines:
- 9-10: Breakthrough, highly novel work
- 7-8: Strong contribution, solid results
- 5-6: Incremental but solid work
- 1-4: Marginal relevance or minor contribution

Be critical and discerning. Not every paper deserves a high score.`;
  const paperList = prepared.map(
    (p, i) => `[${i + 1}] ID: ${p.id}
Title: ${p.title}
Abstract: ${p.summary}`
  ).join("\n---\n");
  const userMessage = `Please score the following ${prepared.length} papers:

${paperList}`;
  const content = await callDeepSeek(apiKey, model, systemPrompt, userMessage);
  const result = JSON.parse(content);
  if (!result.papers || !Array.isArray(result.papers)) {
    throw new Error("Unexpected DeepSeek response format: missing 'papers' array");
  }
  const scored = result.papers;
  scored.sort((a, b) => b.score - a.score);
  return scored;
}
async function summarizePapers(apiKey, model, papers, language) {
  const langHint = language === "zh-CN" ? "\u4E2D\u6587" : "English";
  const systemPrompt = `You are an AI research assistant. Generate a detailed analysis for each paper in ${langHint}.
For each paper, provide:
1. A concise summary (2-3 sentences) of what the paper does
2. 3-5 key bullet points highlighting the main contributions, methods, or findings

Return a JSON object with a "summaries" array:
[{ "id": "paper_id", "summary": "concise summary in ${langHint}", "keyPoints": ["point 1", "point 2", ...] }]

The summary should be informative and capture the essence of the paper. Key points should be specific and technical.`;
  const paperList = papers.map(
    (p, i) => `[${i + 1}] ID: ${p.id}
Title: ${p.title}
Authors: ${p.authors.join(", ")}
Abstract: ${p.summary}`
  ).join("\n---\n");
  const userMessage = `Generate detailed summaries for the following ${papers.length} papers:

${paperList}`;
  const content = await callDeepSeek(apiKey, model, systemPrompt, userMessage);
  const result = JSON.parse(content);
  if (!result.summaries || !Array.isArray(result.summaries)) {
    throw new Error("Unexpected DeepSeek response format: missing 'summaries' array");
  }
  return result.summaries;
}

// src/output.ts
function getDateString() {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, "0");
  const d = String(now.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}
function getTimeString() {
  const now = new Date();
  const hh = String(now.getHours()).padStart(2, "0");
  const mm = String(now.getMinutes()).padStart(2, "0");
  return `${hh}:${mm}`;
}
function getRankEmoji(rank) {
  switch (rank) {
    case 1:
      return "\u{1F3C6}";
    case 2:
      return "\u{1F948}";
    case 3:
      return "\u{1F949}";
    default:
      return `#${rank}`;
  }
}
function generateMarkdown(papers, summaries, totalFetched, language) {
  const isZh = language === "zh-CN";
  const dateStr = getDateString();
  if (isZh) {
    return generateChineseMarkdown(papers, summaries, totalFetched, dateStr);
  }
  return generateEnglishMarkdown(papers, summaries, totalFetched, dateStr);
}
function generateChineseMarkdown(papers, summaries, totalFetched, dateStr) {
  var _a, _b;
  const lines = [];
  const timeStr = getTimeString();
  lines.push(`# \u{1F4C4} Arxiv \u6BCF\u65E5\u8BBA\u6587\u7CBE\u9009 \u2014 ${dateStr}`);
  lines.push("");
  lines.push(`**\u5171\u68C0\u7D22 ${totalFetched} \u7BC7\u8BBA\u6587\uFF0C\u7CBE\u9009 Top ${papers.length}**`);
  lines.push("");
  lines.push(`> \u751F\u6210\u65F6\u95F4: ${dateStr} ${timeStr} | \u4F7F\u7528 DeepSeek AI \u8BC4\u5206\u6392\u5E8F`);
  lines.push("");
  lines.push("---");
  lines.push("");
  const summaryMap = /* @__PURE__ */ new Map();
  for (const s of summaries) {
    summaryMap.set(s.id, s);
  }
  for (let i = 0; i < papers.length; i++) {
    const paper = papers[i];
    const summary = summaryMap.get(paper.id);
    const rank = i + 1;
    const rankEmoji = getRankEmoji(rank);
    const score = (_b = (_a = summary == null ? void 0 : summary.score) == null ? void 0 : _a.toFixed(1)) != null ? _b : "\u2014";
    lines.push(`## ${rankEmoji} Top ${rank} \u2014 ${paper.title} (\u8BC4\u5206: ${score}/10)`);
    lines.push("");
    lines.push(`**\u4F5C\u8005**: ${paper.authors.join(", ")}`);
    lines.push(`**\u94FE\u63A5**: [${paper.link}](${paper.link})`);
    lines.push(`**\u5206\u7C7B**: ${paper.category}`);
    if (summary == null ? void 0 : summary.reason) {
      lines.push(`**\u8BC4\u5206\u7406\u7531**: ${summary.reason}`);
    }
    lines.push("");
    if (summary == null ? void 0 : summary.summary) {
      lines.push("### \u{1F4DD} \u6458\u8981");
      lines.push("");
      lines.push(summary.summary);
      lines.push("");
    }
    if ((summary == null ? void 0 : summary.keyPoints) && summary.keyPoints.length > 0) {
      lines.push("### \u{1F511} \u6838\u5FC3\u8981\u70B9");
      lines.push("");
      for (const point of summary.keyPoints) {
        lines.push(`- ${point}`);
      }
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }
  lines.push(
    `*\u672C\u65E5\u62A5\u7531 DailyArticle \u63D2\u4EF6\u81EA\u52A8\u751F\u6210\uFF0C\u4F7F\u7528 DeepSeek API \u8FDB\u884C\u667A\u80FD\u8BC4\u5206\u4E0E\u6458\u8981*`
  );
  lines.push("");
  return lines.join("\n");
}
function generateEnglishMarkdown(papers, summaries, totalFetched, dateStr) {
  var _a, _b;
  const lines = [];
  const timeStr = getTimeString();
  lines.push(`# \u{1F4C4} Arxiv Daily Paper Digest \u2014 ${dateStr}`);
  lines.push("");
  lines.push(`**${totalFetched} papers retrieved, Top ${papers.length} selected**`);
  lines.push("");
  lines.push(`> Generated: ${dateStr} ${timeStr} | Scored by DeepSeek AI`);
  lines.push("");
  lines.push("---");
  lines.push("");
  const summaryMap = /* @__PURE__ */ new Map();
  for (const s of summaries) {
    summaryMap.set(s.id, s);
  }
  for (let i = 0; i < papers.length; i++) {
    const paper = papers[i];
    const summary = summaryMap.get(paper.id);
    const rank = i + 1;
    const rankEmoji = getRankEmoji(rank);
    const score = (_b = (_a = summary == null ? void 0 : summary.score) == null ? void 0 : _a.toFixed(1)) != null ? _b : "\u2014";
    lines.push(`## ${rankEmoji} Top ${rank} \u2014 ${paper.title} (Score: ${score}/10)`);
    lines.push("");
    lines.push(`**Authors**: ${paper.authors.join(", ")}`);
    lines.push(`**Link**: [${paper.link}](${paper.link})`);
    lines.push(`**Category**: ${paper.category}`);
    if (summary == null ? void 0 : summary.reason) {
      lines.push(`**Scoring Reason**: ${summary.reason}`);
    }
    lines.push("");
    if (summary == null ? void 0 : summary.summary) {
      lines.push("### \u{1F4DD} Summary");
      lines.push("");
      lines.push(summary.summary);
      lines.push("");
    }
    if ((summary == null ? void 0 : summary.keyPoints) && summary.keyPoints.length > 0) {
      lines.push("### \u{1F511} Key Points");
      lines.push("");
      for (const point of summary.keyPoints) {
        lines.push(`- ${point}`);
      }
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }
  lines.push(
    "*This digest was automatically generated by the DailyArticle plugin using DeepSeek API for scoring and summarization.*"
  );
  lines.push("");
  return lines.join("\n");
}
function getOutputFilename() {
  return `Arxiv-\u65E5\u62A5-${getDateString()}.md`;
}

// src/main.ts
var DailyArticlePlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.lastFetchDate = "";
  }
  async onload() {
    try {
      await this.loadSettings();
      this.addSettingTab(new DailyArticleSettingTab(this.app, this));
      this.addCommand({
        id: "fetch-today-papers",
        name: "\u7ACB\u5373\u83B7\u53D6\u4ECA\u65E5\u8BBA\u6587",
        callback: () => {
          this.fetchAndProcess();
        }
      });
      this.addCommand({
        id: "test-deepseek-connection",
        name: "\u6D4B\u8BD5 DeepSeek API \u8FDE\u63A5",
        callback: () => {
          this.testConnection();
        }
      });
      const intervalId = window.setInterval(() => {
        this.checkScheduledFetch();
      }, 6e4);
      this.registerInterval(intervalId);
      console.log("DailyArticle plugin loaded");
    } catch (e) {
      console.error("DailyArticle plugin failed to load:", e);
    }
  }
  onunload() {
    console.log("DailyArticle plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  parseCategories() {
    return this.settings.arxivCategories.split("\n").map((c) => c.trim()).filter((c) => c.length > 0);
  }
  async testConnection() {
    if (!this.settings.deepseekApiKey) {
      new import_obsidian2.Notice("\u274C \u8BF7\u5148\u586B\u5199 DeepSeek API Key");
      return;
    }
    new import_obsidian2.Notice("\u{1F504} \u6B63\u5728\u6D4B\u8BD5 DeepSeek API \u8FDE\u63A5...");
    try {
      const response = await fetch("https://api.deepseek.com/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${this.settings.deepseekApiKey}`
        },
        body: JSON.stringify({
          model: this.settings.model,
          messages: [
            { role: "user", content: "Hello" }
          ],
          max_tokens: 10
        })
      });
      if (response.ok) {
        new import_obsidian2.Notice("\u2705 DeepSeek API \u8FDE\u63A5\u6210\u529F\uFF01");
      } else {
        const text = await response.text();
        new import_obsidian2.Notice(`\u274C API \u8FDE\u63A5\u5931\u8D25: ${response.status} ${text.slice(0, 100)}`);
      }
    } catch (e) {
      new import_obsidian2.Notice(`\u274C \u7F51\u7EDC\u9519\u8BEF: ${e.message}`);
    }
  }
  checkScheduledFetch() {
    if (!this.settings.fetchTime)
      return;
    const now = new Date();
    const todayStr = now.toISOString().slice(0, 10);
    if (this.lastFetchDate === todayStr)
      return;
    const [targetHour, targetMin] = this.settings.fetchTime.split(":").map(Number);
    if (now.getHours() === targetHour && now.getMinutes() === targetMin) {
      this.lastFetchDate = todayStr;
      this.fetchAndProcess();
    }
  }
  async fetchAndProcess() {
    if (!this.settings.deepseekApiKey) {
      new import_obsidian2.Notice("\u274C \u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u586B\u5199 DeepSeek API Key");
      return;
    }
    const categories = this.parseCategories();
    if (categories.length === 0) {
      new import_obsidian2.Notice("\u274C \u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u586B\u5199 Arxiv \u5206\u7C7B");
      return;
    }
    new import_obsidian2.Notice("\u{1F504} \u6B63\u5728\u4ECE Arxiv \u83B7\u53D6\u8BBA\u6587...");
    try {
      const allPapers = await fetchPapersByCategories(
        categories,
        this.settings.maxResultsPerCategory
      );
      if (allPapers.length === 0) {
        new import_obsidian2.Notice("\u26A0\uFE0F \u4ECA\u65E5 Arxiv \u6682\u65E0\u65B0\u8BBA\u6587");
        return;
      }
      new import_obsidian2.Notice(`\u{1F4DA} \u5DF2\u83B7\u53D6 ${allPapers.length} \u7BC7\u8BBA\u6587\uFF0C\u6B63\u5728\u8BC4\u5206...`);
      const scoredPapers = await scorePapers(
        this.settings.deepseekApiKey,
        this.settings.model,
        allPapers,
        this.settings.outputLanguage
      );
      const topN = this.settings.topN;
      const topScoredIds = new Set(
        scoredPapers.slice(0, topN).map((sp) => sp.id)
      );
      const scoredMap = /* @__PURE__ */ new Map();
      for (const sp of scoredPapers) {
        scoredMap.set(sp.id, sp);
      }
      const topPapers = [];
      for (const sp of scoredPapers.slice(0, topN)) {
        const paper = allPapers.find((p) => p.id === sp.id);
        if (paper) {
          topPapers.push(paper);
        }
      }
      new import_obsidian2.Notice(`\u{1F4DD} \u6B63\u5728\u751F\u6210 Top ${topPapers.length} \u8BBA\u6587\u6458\u8981...`);
      const summaries = await summarizePapers(
        this.settings.deepseekApiKey,
        this.settings.model,
        topPapers,
        this.settings.outputLanguage
      );
      const enrichedSummaries = summaries.map((s) => {
        var _a, _b;
        const scored = scoredMap.get(s.id);
        return {
          ...s,
          score: (_a = scored == null ? void 0 : scored.score) != null ? _a : 0,
          reason: (_b = scored == null ? void 0 : scored.reason) != null ? _b : ""
        };
      });
      const markdown = generateMarkdown(
        topPapers,
        enrichedSummaries,
        allPapers.length,
        this.settings.outputLanguage
      );
      await this.writeOutputFile(markdown);
      new import_obsidian2.Notice(
        `\u2705 \u65E5\u62A5\u5DF2\u751F\u6210\uFF01\u5171 ${allPapers.length} \u7BC7\uFF0C\u7CBE\u9009 Top ${topPapers.length}`
      );
    } catch (e) {
      console.error("DailyArticle fetch error:", e);
      new import_obsidian2.Notice(`\u274C \u5904\u7406\u5931\u8D25: ${e.message}`);
    }
  }
  async writeOutputFile(content) {
    const folderPath = this.settings.outputFolder;
    const fileName = getOutputFilename();
    const filePath = `${folderPath}/${fileName}`;
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await this.app.vault.createFolder(folderPath);
    }
    const existingFile = this.app.vault.getAbstractFileByPath(filePath);
    if (existingFile instanceof import_obsidian2.TFile) {
      await this.app.vault.modify(existingFile, content);
    } else {
      await this.app.vault.create(filePath, content);
    }
  }
};
