import { ArxivPaper } from "./arxiv";
import { PaperSummary } from "./deepseek";

function getDateString(date?: Date): string {
  const d = date || new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function getTimeString(): string {
  const now = new Date();
  const hh = String(now.getHours()).padStart(2, "0");
  const mm = String(now.getMinutes()).padStart(2, "0");
  return `${hh}:${mm}`;
}

function getRankEmoji(rank: number): string {
  switch (rank) {
    case 1:
      return "🏆";
    case 2:
      return "🥈";
    case 3:
      return "🥉";
    default:
      return `#${rank}`;
  }
}

/**
 * Generate the Markdown content for the daily article.
 */
export function generateMarkdown(
  papers: ArxivPaper[],
  summaries: PaperSummary[],
  totalFetched: number,
  language: string,
  date?: Date
): string {
  const isZh = language === "zh-CN";
  const dateStr = getDateString(date);

  if (isZh) {
    return generateChineseMarkdown(papers, summaries, totalFetched, dateStr);
  }
  return generateEnglishMarkdown(papers, summaries, totalFetched, dateStr);
}

function generateChineseMarkdown(
  papers: ArxivPaper[],
  summaries: PaperSummary[],
  totalFetched: number,
  dateStr: string
): string {
  const lines: string[] = [];
  const timeStr = getTimeString();

  lines.push(`# 📄 Arxiv 每日论文精选 — ${dateStr}`);
  lines.push("");
  lines.push(`**共检索 ${totalFetched} 篇论文，精选 Top ${papers.length}**`);
  lines.push("");
  lines.push(`> 生成时间: ${dateStr} ${timeStr} | 使用 DeepSeek AI 评分排序`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Build a map for quick lookup
  const summaryMap = new Map<string, PaperSummary>();
  for (const s of summaries) {
    summaryMap.set(s.id, s);
  }

  for (let i = 0; i < papers.length; i++) {
    const paper = papers[i];
    const summary = summaryMap.get(paper.id);
    const rank = i + 1;
    const rankEmoji = getRankEmoji(rank);
    const score = summary?.score?.toFixed(1) ?? "—";

    lines.push(`## ${rankEmoji} Top ${rank} — ${paper.title} (评分: ${score}/10)`);
    lines.push("");
    lines.push(`**作者**: ${paper.authors.join(", ")}`);
    lines.push(`**链接**: [${paper.link}](${paper.link})`);
    lines.push(`**分类**: ${paper.category}`);
    if (summary?.reason) {
      lines.push(`**评分理由**: ${summary.reason}`);
    }
    lines.push("");

    if (summary?.summary) {
      lines.push("### 📝 摘要");
      lines.push("");
      lines.push(summary.summary);
      lines.push("");
    }

    if (summary?.keyPoints && summary.keyPoints.length > 0) {
      lines.push("### 🔑 核心要点");
      lines.push("");
      for (const point of summary.keyPoints) {
        lines.push(`- ${point}`);
      }
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  }

  lines.push(
    `*本日报由 DailyArticle 插件自动生成，使用 DeepSeek API 进行智能评分与摘要*`
  );
  lines.push("");

  return lines.join("\n");
}

function generateEnglishMarkdown(
  papers: ArxivPaper[],
  summaries: PaperSummary[],
  totalFetched: number,
  dateStr: string
): string {
  const lines: string[] = [];
  const timeStr = getTimeString();

  lines.push(`# 📄 Arxiv Daily Paper Digest — ${dateStr}`);
  lines.push("");
  lines.push(`**${totalFetched} papers retrieved, Top ${papers.length} selected**`);
  lines.push("");
  lines.push(`> Generated: ${dateStr} ${timeStr} | Scored by DeepSeek AI`);
  lines.push("");
  lines.push("---");
  lines.push("");

  const summaryMap = new Map<string, PaperSummary>();
  for (const s of summaries) {
    summaryMap.set(s.id, s);
  }

  for (let i = 0; i < papers.length; i++) {
    const paper = papers[i];
    const summary = summaryMap.get(paper.id);
    const rank = i + 1;
    const rankEmoji = getRankEmoji(rank);
    const score = summary?.score?.toFixed(1) ?? "—";

    lines.push(`## ${rankEmoji} Top ${rank} — ${paper.title} (Score: ${score}/10)`);
    lines.push("");
    lines.push(`**Authors**: ${paper.authors.join(", ")}`);
    lines.push(`**Link**: [${paper.link}](${paper.link})`);
    lines.push(`**Category**: ${paper.category}`);
    if (summary?.reason) {
      lines.push(`**Scoring Reason**: ${summary.reason}`);
    }
    lines.push("");

    if (summary?.summary) {
      lines.push("### 📝 Summary");
      lines.push("");
      lines.push(summary.summary);
      lines.push("");
    }

    if (summary?.keyPoints && summary.keyPoints.length > 0) {
      lines.push("### 🔑 Key Points");
      lines.push("");
      for (const point of summary.keyPoints) {
        lines.push(`- ${point}`);
      }
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  }

  lines.push(
    "*This digest was automatically generated by the DailyArticle plugin using DeepSeek API for scoring and summarization.*"
  );
  lines.push("");

  return lines.join("\n");
}

/**
 * Generate a filename for the daily article.
 */
export function getOutputFilename(date?: Date): string {
  return `Arxiv-日报-${getDateString(date)}.md`;
}
